### PR TITLE
Feature/add order documentation

### PR DESCRIPTION
**Pull request by TxHawks**
The PR add documentation to the `order` feature discussed in jonathantneal/mdcss#10.

Please see [README.md#L75](https://github.com/jonathantneal/mdcss-theme-github/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R75) to check that I got section ordering right.

### CODE REVIEW

**Comment by jonathantneal** [comment]
Great work! I have made one comment, and I’ll be happy to get this in today.

**Comment by TxHawks** [comment]
Oops... 
Done

**Comment by jonathantneal** [comment]
Excellent work, @TxHawks. Thank you so much. Great squashing, too! Ah, I love collaboration.

**Comment by TxHawks** [comment]
Happy to be able to give (very little, I know) back.

**Pull request merged**
